algoritmo "teste se e senao"
// Função :
// Autor :
// Data : 29/09/2022
// Seção de Declarações 
var

nmr1, nmr2: inteiro

inicio
// Seção de Comandos
   escreva(" digite o primeiro número: ")
   leia (nmr1)
   escreva ("digite o sewegundo numero: ")
   leia (nmr2)
se(nmr1 = nmr2)entao
    escreva("os numeros são iguais.")
senao
se(nmr1 > nmr2)entao
    escreva("o maior valor é = ", nmr1)
senao
    escreva ("o maior valor é = ", nmr2)
    
    fimse
   
fimse
fimalgoritmo
